#!/bin/bash
echo "_|    _|                      _|            _|                  _|"
echo "_|    _|    _|_|_|    _|_|_|  _|  _|        _|          _|_|_|  _|_|_|"
echo "_|_|_|_|  _|    _|  _|        _|_|          _|        _|    _|  _|    _|"
echo "_|    _|  _|    _|  _|        _|  _|        _|        _|    _|  _|    _|"
echo "_|    _|    _|_|_|    _|_|_|  _|    _|      _|_|_|_|    _|_|_|  _|_|_|"
echo "                                                                      "


	if [ $REPLY != "y" ]; then
		echo "Exiting..."
		exit 1
	fi

if [ $1 = "noob" ]
  then
    echo "Shell: http://${IP_LOCAL}:4200"
    cd /root/local/shellinabox && ./shellinaboxd -t -q
    echo "Log in, and run: cd /root/local/meteoroid/start"
    
  else
    IP_LOCAL=$(/sbin/ifconfig | sed -n '2 p' | awk '{print $2}' | cut -d':' -f 2)
    
    echo "Cloud9 IDE: http://${IP_LOCAL}:3131"
    
    echo "Secure Shell: https://${IP_LOCAL}:12320"
    
    echo "Webmin: https://${IP_LOCAL}:12321"
    
    echo "Meteoroid Docs: http://${IP_LOCAL}:8181"
    
    echo "SSH/SFTP root@${IP_LOCAL} port 22"
    
    echo "Mongo DB mongo -u admin -p <password> ${IP_LOCAL}[/DB]"
    
    echo "RockMongo https://${IP_LOCAL}"
    
    /root/local/cloud9/bin/cloud9.sh -p 3131 -l 0.0.0.0 -w / > /dev/null &
    
    export MONGO_URL=mongodb://admin:password@localhost:27017/meteoroid
    
    cd /root/meteoroid && mrt --port 8181 > /dev/null
fi
